CREATE DATABASE IF NOT EXISTS rsoa_rsoa278_10;
USE rsoa_rsoa278_10;

CREATE TABLE IF NOT EXISTS registered_domains (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain_name VARCHAR(255) NOT NULL UNIQUE,
    extension VARCHAR(10) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
